<a href="https://colab.research.google.com/github/Akshayextreme/Fake_news_detection_hackathon/blob/master/Fake_news_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.34.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.12.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.17.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.15,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.1)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2023.7.22)

In [ ]:
import numpy as np
import pandas as pd
from sklearn import metrics
import transformers
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer

In [ ]:
from torch import cuda
device = 'cuda' if cuda.is_available() else 'cpu'

In [ ]:
df = pd.read_csv('Train.csv')

In [ ]:
df.head()

,Labels,Text,Text_Tag
0,1,Says the Annies List political group supports ...,abortion
1,2,When did the decline of coal start? It started...,"energy,history,job-accomplishments"
2,3,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy
3,1,Health care reform legislation is likely to ma...,health-care
4,2,The economic turnaround started at the end of ...,"economy,jobs"

In [ ]:
df.isnull().sum()

Labels      0
Text        0
Text_Tag    2
dtype: int64

In [ ]:
df.Text_Tag.fillna('Not Available', inplace=True)

In [ ]:
df['Text_Tag'] = df.Text_Tag.str.replace(",", " ")

In [ ]:
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

In [ ]:
def leng_txt(x):
    in_ids = tokenizer.encode(x, add_special_tokens=True)
    return len(in_ids)

In [ ]:
df['length'] = df.Text.apply(leng_txt)

Token indices sequence length is longer than the specified maximum sequence length for this model (714 > 512). Running this sequence through the model will result in indexing errors

In [ ]:
df.length.quantile(0.95)

42.0

In [ ]:
df.length.median()

22.0

In [ ]:
MAX_LEN = 50
TRAIN_BATCH_SIZE = 64
VALID_BATCH_SIZE = 32
LEARNING_RATE = 1e-05

In [ ]:
class CustomDataset(Dataset):
    def __init__(self, dataframe, tokenizer, max_len):
        self.data = dataframe
        self.text = dataframe.Text
        self.targets = dataframe.Labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.text)

    def __getitem__(self, idx):
        text = str(self.text[idx])
        text = " ".join(text.split())

        inputs = self.tokenizer.encode_plus(
            text,
            None,
            max_length=self.max_len,
            padding='max_length',
            return_token_type_ids=True,
            truncation=True
        )
        ids = inputs['input_ids']
        mask = inputs['attention_mask']
        token_type_ids = inputs["token_type_ids"]


        return {
            'ids': torch.tensor(ids, dtype=torch.long),
            'mask': torch.tensor(mask, dtype=torch.long),
            'token_type_ids': torch.tensor(token_type_ids, dtype=torch.long),
            'targets': torch.tensor(self.targets[idx], dtype=torch.long)
        }

In [ ]:
train_size = 0.8
train_dataset=df.sample(frac=train_size,random_state=648)
val_dataset=df.drop(train_dataset.index).reset_index(drop=True)
train_dataset = train_dataset.reset_index(drop=True)


print("FULL Dataset: {}".format(df.shape))
print("TRAIN Dataset: {}".format(train_dataset.shape))
print("TEST Dataset: {}".format(val_dataset.shape))

training_set = CustomDataset(train_dataset, tokenizer, MAX_LEN)
validation_set = CustomDataset(val_dataset, tokenizer, MAX_LEN)

FULL Dataset: (10240, 4)
TRAIN Dataset: (8192, 4)
TEST Dataset: (2048, 4)

In [ ]:
train_params = {'batch_size': TRAIN_BATCH_SIZE,
                'shuffle': True,
                'num_workers': 4
                }

test_params = {'batch_size': VALID_BATCH_SIZE,
                'shuffle': True,
                'num_workers': 4
                }

training_loader = DataLoader(training_set, **train_params)
validation_loader = DataLoader(validation_set, **test_params)

/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(

In [ ]:
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels = 6,
    output_attentions = False,
    output_hidden_states = False,
)

model.to(device)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['pre_classifier.weight', 'classifier.bias', 'classifier.weight', 'pre_classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): MultiHeadSelfAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=6, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
optimizer = torch.optim.Adam(params =  model.parameters(), lr=LEARNING_RATE)

In [ ]:
from transformers import get_linear_schedule_with_warmup
EPOCHS = 30
total_steps = len(training_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(optimizer,
                                            num_warmup_steps = 0,
                                            num_training_steps = total_steps)

In [ ]:
def validation(epoch):
    model.eval()
    running_loss = 0.0
    running_corrects = 0

    with torch.no_grad():
        for _, data in enumerate(validation_loader, 0):
            ids = data['ids'].to(device, dtype = torch.long)
            mask = data['mask'].to(device, dtype = torch.long)
            token_type_ids = data['token_type_ids'].to(device, dtype = torch.long)
            targets = data['targets'].to(device, dtype = torch.long)

            loss, outputs = model(ids, mask, labels=targets,  return_dict=False)
            preds = torch.argmax(outputs, 1)

            running_loss += loss.item()
            running_corrects += torch.sum(preds == targets.data)

        epoch_loss = running_loss / validation_set.__len__()
        epoch_acc = running_corrects.double() / validation_set.__len__()

        print(f'Valid -> Epoch: {epoch}, Loss: {epoch_loss}, Accuracy: {epoch_acc}')
        print('\n ==================================================================== \n')
        return epoch_acc

In [ ]:
def train(epoch):
    model.train()
    running_loss = 0.0
    running_corrects = 0

    for i, data in enumerate(training_loader, 0):
        ids = data['ids'].to(device, dtype = torch.long)
        mask = data['mask'].to(device, dtype = torch.long)
        token_type_ids = data['token_type_ids'].to(device, dtype = torch.long)
        targets = data['targets'].to(device, dtype = torch.long)

        loss, outputs = model(ids, mask, labels=targets, return_dict=False)
        preds = torch.argmax(outputs, 1)

        optimizer.zero_grad()

        running_loss += loss.item()
        running_corrects += torch.sum(preds == targets.data)

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        scheduler.step()

    epoch_loss = running_loss / training_set.__len__()
    epoch_acc = running_corrects.double() / training_set.__len__()
    print(f'Train -> Epoch: {epoch}, Loss: {epoch_loss}, Accuracy: {epoch_acc}')

In [ ]:
import copy
best_model_wts = copy.deepcopy(model.state_dict())
best_acc = 0.0

for epoch in range(EPOCHS):
    train(epoch)
    epoch_acc = validation(epoch)
    if epoch_acc > best_acc:
        best_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())

model.load_state_dict(best_model_wts)
print(f'Best Valid Acc: {best_acc}')

Train -> Epoch: 0, Loss: 0.02523192556691356, Accuracy: 0.3240966796875
Valid -> Epoch: 0, Loss: 0.052398275467567146, Accuracy: 0.26318359375

 ====================================================================

Train -> Epoch: 1, Loss: 0.024401132643106394, Accuracy: 0.36572265625
Valid -> Epoch: 1, Loss: 0.052679625048767775, Accuracy: 0.2705078125

 ====================================================================

Train -> Epoch: 2, Loss: 0.023277245709323324, Accuracy: 0.4024658203125
Valid -> Epoch: 2, Loss: 0.053145208570640534, Accuracy: 0.27587890625

 ====================================================================

Train -> Epoch: 3, Loss: 0.022217662670300342, Accuracy: 0.441162109375
Valid -> Epoch: 3, Loss: 0.05421661405125633, Accuracy: 0.265625

 ====================================================================

Train -> Epoch: 4, Loss: 0.020991119206883013, Accuracy: 0.47900390625
Valid -> Epoch: 4, Loss: 0.05556525313295424, Accuracy: 0.263671875

 ====================================================================

Train -> Epoch: 5, Loss: 0.019855501581332646, Accuracy: 0.52001953125
Valid -> Epoch: 5, Loss: 0.05709492013556883, Accuracy: 0.26220703125

 ====================================================================

Train -> Epoch: 6, Loss: 0.018608463760756422, Accuracy: 0.55517578125
Valid -> Epoch: 6, Loss: 0.05901740776607767, Accuracy: 0.25830078125

 ====================================================================

Train -> Epoch: 7, Loss: 0.017502869297459256, Accuracy: 0.5889892578125
Valid -> Epoch: 7, Loss: 0.060373087879270315, Accuracy: 0.265625

 ====================================================================

Train -> Epoch: 8, Loss: 0.01640587158908602, Accuracy: 0.6212158203125
Valid -> Epoch: 8, Loss: 0.06226192635949701, Accuracy: 0.259765625

 ====================================================================

Train -> Epoch: 9, Loss: 0.015347146771091502, Accuracy: 0.64453125
Valid -> Epoch: 9, Loss: 0.06401438941247761, Accuracy: 0.251953125

 ====================================================================

Train -> Epoch: 10, Loss: 0.01430170417734189, Accuracy: 0.6744384765625
Valid -> Epoch: 10, Loss: 0.0660812680143863, Accuracy: 0.24951171875

 ====================================================================

Train -> Epoch: 11, Loss: 0.013276290432258975, Accuracy: 0.7015380859375
Valid -> Epoch: 11, Loss: 0.06836304132593796, Accuracy: 0.24755859375

 ====================================================================

Train -> Epoch: 12, Loss: 0.012378495259326883, Accuracy: 0.72998046875
Valid -> Epoch: 12, Loss: 0.07014067430282012, Accuracy: 0.2548828125

 ====================================================================

Train -> Epoch: 13, Loss: 0.011620863384450786, Accuracy: 0.7437744140625
Valid -> Epoch: 13, Loss: 0.07197478564921767, Accuracy: 0.2490234375

 ====================================================================

Train -> Epoch: 14, Loss: 0.010898563257796923, Accuracy: 0.767333984375
Valid -> Epoch: 14, Loss: 0.07325230143032968, Accuracy: 0.24951171875

 ====================================================================

Train -> Epoch: 15, Loss: 0.010341707547922852, Accuracy: 0.7760009765625
Valid -> Epoch: 15, Loss: 0.07474271138198674, Accuracy: 0.24658203125

 ====================================================================

Train -> Epoch: 16, Loss: 0.009689499234809773, Accuracy: 0.7923583984375
Valid -> Epoch: 16, Loss: 0.07633642113069072, Accuracy: 0.2490234375

 ====================================================================

Train -> Epoch: 17, Loss: 0.009125357420998625, Accuracy: 0.803466796875
Valid -> Epoch: 17, Loss: 0.07827878388343379, Accuracy: 0.255859375

 ====================================================================

Train -> Epoch: 18, Loss: 0.008599520144343842, Accuracy: 0.8223876953125
Valid -> Epoch: 18, Loss: 0.07967537106014788, Accuracy: 0.24951171875

 ====================================================================

Train -> Epoch: 19, Loss: 0.008167457515810383, Accuracy: 0.8321533203125
Valid -> Epoch: 19, Loss: 0.08112672745482996, Accuracy: 0.24462890625

 ====================================================================

Train -> Epoch: 20, Loss: 0.00787729747753474, Accuracy: 0.8402099609375
Valid -> Epoch: 20, Loss: 0.08153340895660222, Accuracy: 0.25146484375

 ====================================================================

Train -> Epoch: 21, Loss: 0.007496584912587423, Accuracy: 0.843505859375
Valid -> Epoch: 21, Loss: 0.08248620817903429, Accuracy: 0.251953125

 ====================================================================

Train -> Epoch: 22, Loss: 0.007298915668798145, Accuracy: 0.8531494140625
Valid -> Epoch: 22, Loss: 0.08364957827143371, Accuracy: 0.24853515625

 ====================================================================

Train -> Epoch: 23, Loss: 0.0070371169967984315, Accuracy: 0.857421875
Valid -> Epoch: 23, Loss: 0.08385021367575973, Accuracy: 0.24853515625

 ====================================================================

Train -> Epoch: 24, Loss: 0.006910374933795538, Accuracy: 0.8592529296875
Valid -> Epoch: 24, Loss: 0.08451203908771276, Accuracy: 0.248046875

 ====================================================================

Train -> Epoch: 25, Loss: 0.006707912234560354, Accuracy: 0.8671875
Valid -> Epoch: 25, Loss: 0.08498257445171475, Accuracy: 0.2509765625

 ====================================================================

Train -> Epoch: 26, Loss: 0.006679010624793591, Accuracy: 0.8692626953125
Valid -> Epoch: 26, Loss: 0.08492425864096731, Accuracy: 0.25

 ====================================================================

Train -> Epoch: 27, Loss: 0.006693571973301005, Accuracy: 0.8638916015625
Valid -> Epoch: 27, Loss: 0.08492425829172134, Accuracy: 0.25

 ====================================================================

Train -> Epoch: 28, Loss: 0.006724074894009391, Accuracy: 0.8634033203125
Valid -> Epoch: 28, Loss: 0.08492425864096731, Accuracy: 0.25

 ====================================================================

Train -> Epoch: 29, Loss: 0.006764981000742409, Accuracy: 0.8626708984375
Valid -> Epoch: 29, Loss: 0.08492425887379795, Accuracy: 0.25

 ====================================================================

Best Valid Acc: 0.27587890625

In [ ]:
model.save_pretrained(r"C:\Users\Meena\Downloads\Fake News Pred")
model.config.save_pretrained(r"C:\Users\Meena\Downloads\Fake News Pred")

### Test

In [ ]:
df_test = pd.read_csv('Test.csv')
df_test['Labels'] = 0

In [ ]:
df_test['Text_Tag'] = df_test.Text_Tag.str.replace(",", " ")

In [ ]:
df_test['length'] = df_test.Text.apply(leng_txt)
df_test.length.quantile(0.95)

41.0

In [ ]:
testing_set = CustomDataset(df_test, tokenizer, MAX_LEN)
TEST_BATCH_SIZE = 32
test_params = {'batch_size': TEST_BATCH_SIZE,
                'shuffle': False,
                'num_workers': 4
                }
testing_loader = DataLoader(testing_set, **test_params)

/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(

In [ ]:
proba = torch.nn.Softmax(dim=1)

def test():
    model.eval()
    prediction = []

    with torch.no_grad():
        for i, data in enumerate(testing_loader, 0):
            ids = data['ids'].to(device, dtype = torch.long)
            mask = data['mask'].to(device, dtype = torch.long)
            token_type_ids = data['token_type_ids'].to(device, dtype = torch.long)
            outputs = model(ids, mask)
            outputs = proba(outputs[0])
            outputs = outputs.detach().cpu().numpy()
            prediction.append(outputs)
        return prediction

In [ ]:
tmp = test()

In [ ]:
submit = pd.DataFrame(np.vstack(tmp))

In [ ]:
submit.to_csv('submit.csv', index=False)

In [ ]:
submit

             0         1         2         3         4         5
0     0.196518  0.424252  0.130565  0.047329  0.151098  0.050239
1     0.096443  0.095540  0.433905  0.230108  0.025010  0.118995
2     0.325665  0.291296  0.135231  0.072313  0.068706  0.106789
3     0.392682  0.273385  0.158150  0.042405  0.098953  0.034424
4     0.179562  0.180745  0.232442  0.143677  0.055144  0.208430
...        ...       ...       ...       ...       ...       ...
1262  0.060289  0.114713  0.120878  0.387473  0.019160  0.297487
1263  0.193930  0.260595  0.152594  0.123361  0.085424  0.184097
1264  0.279242  0.224301  0.163940  0.097174  0.115844  0.119499
1265  0.332718  0.234525  0.129954  0.086224  0.151101  0.065479
1266  0.218280  0.209876  0.336501  0.082537  0.033512  0.119295

[1267 rows x 6 columns]